sudo: required
services:
  - docker

before_install:
  - docker build -t aleksgor/docker-react -f Dockerfile.dev .

script:
  - docker run aleksgor/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "u-docker-react"
  env: "Udockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-422701111692"
  bucket_path: "u-docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
